import type { CamModel } from "@/lib/models/types";

/** Placeholder catalog biased toward mature / MILF niche until live APIs are wired. */
export const PLACEHOLDER_MODELS: CamModel[] = [
  {
    id: "m1",
    username: "maturevelvet",
    displayName: "MatureVelvet",
    age: 42,
    tags: ["milf", "mature", "curvy"],
    viewers: 1842,
    isLive: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=640&q=80&auto=format&fit=crop",
    platform: "stripchat",
    countryCode: "US",
  },
  {
    id: "m2",
    username: "cougarluxe",
    displayName: "CougarLuxe",
    age: 38,
    tags: ["cougar", "milf", "blonde"],
    viewers: 956,
    isLive: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=640&q=80&auto=format&fit=crop",
    platform: "chaturbate",
    countryCode: "CA",
  },
  {
    id: "m3",
    username: "momnextdoor",
    displayName: "MomNextDoor",
    age: 45,
    tags: ["mom", "mature", "natural"],
    viewers: 2103,
    isLive: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=640&q=80&auto=format&fit=crop",
    platform: "stripchat",
    countryCode: "GB",
  },
  {
    id: "m4",
    username: "silverfoxlive",
    displayName: "SilverFoxLive",
    age: 51,
    tags: ["mature", "gilf", "elegant"],
    viewers: 744,
    isLive: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=640&q=80&auto=format&fit=crop",
    platform: "crak",
    countryCode: "DE",
  },
  {
    id: "m5",
    username: "hotmilfhouse",
    displayName: "HotMilfHouse",
    age: 36,
    tags: ["milf", "latina", "mature"],
    viewers: 1320,
    isLive: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=640&q=80&auto=format&fit=crop",
    platform: "chaturbate",
    countryCode: "ES",
  },
  {
    id: "m6",
    username: "classymature",
    displayName: "ClassyMature",
    age: 48,
    tags: ["mature", "cougar", "lingerie"],
    viewers: 621,
    isLive: false,
    thumbnailUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=640&q=80&auto=format&fit=crop",
    platform: "stripchat",
    countryCode: "FR",
  },
  {
    id: "m7",
    username: "redheadmama",
    displayName: "RedheadMama",
    age: 39,
    tags: ["mom", "milf", "redhead"],
    viewers: 1588,
    isLive: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=640&q=80&auto=format&fit=crop",
    platform: "stripchat",
    countryCode: "US",
  },
  {
    id: "m8",
    username: "maturegoddess",
    displayName: "MatureGoddess",
    age: 44,
    tags: ["mature", "bbw", "milf"],
    viewers: 892,
    isLive: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=640&q=80&auto=format&fit=crop",
    platform: "chaturbate",
    countryCode: "AU",
  },
];
