import { Model } from '@/types/model';

export const MOCK_MODELS: Model[] = [
  {
    id: '1',
    name: 'Elena_Vance',
    age: 42,
    rating: 4.9,
    viewers: 1420,
    tags: ['Mature', 'Natural', 'Big Tits', 'Multilingual'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    isOnline: true,
    isHD: true,
    country: 'US',
  },
  {
    id: '2',
    name: 'Sofia_Mila',
    age: 39,
    rating: 4.8,
    viewers: 980,
    tags: ['Milf', 'Curvy', 'Oil', 'Tease'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    isOnline: true,
    isHD: true,
    country: 'ES',
  },
  {
    id: '3',
    name: 'Clara_Hot',
    age: 45,
    rating: 4.7,
    viewers: 750,
    tags: ['Mature', 'Experienced', 'Toys', 'Hot'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    isOnline: true,
    isHD: false,
    country: 'CO',
  },
  {
    id: '4',
    name: 'Victoria_Boss',
    age: 41,
    rating: 4.9,
    viewers: 2100,
    tags: ['Milf', 'Glamour', 'HD', 'Interactive'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    isOnline: true,
    isHD: true,
    country: 'BR',
  },
];
