import { Model } from '@/types/model';
export const MOCK_MODELS: Model[] = [
  {
    id: '1',
    username: 'sophia_mature',
    displayName: 'Sophia Lux',
    age: 42,
    country: 'United States',
    countryCode: 'US',
    categories: ['mature', 'milf', 'popular'],
    thumbnail: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    isLive: true,
    viewerCount: 1240,
    destinationUrl: 'https://your-jerkmate-smartlink-here.com',
  },
  {
    id: '2',
    username: 'elena_sensual',
    displayName: 'Elena Vance',
    age: 46,
    country: 'Spain',
    countryCode: 'ES',
    categories: ['mature', 'new'],
    thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    isLive: true,
    viewerCount: 850,
    destinationUrl: 'https://your-jerkmate-smartlink-here.com',
  },
  {
    id: '3',
    username: 'victoria_milf',
    displayName: 'Victoria Secret',
    age: 39,
    country: 'Canada',
    countryCode: 'CA',
    categories: ['milf', 'popular'],
    thumbnail: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    isLive: true,
    viewerCount: 2100,
    destinationUrl: 'https://your-jerkmate-smartlink-here.com',
  },
  {
    id: '4',
    username: 'clara_mature_vip',
    displayName: 'Clara Belle',
    age: 44,
    country: 'United Kingdom',
    countryCode: 'GB',
    categories: ['mature', 'milf'],
    thumbnail: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    isLive: false,
    viewerCount: 0,
    destinationUrl: 'https://your-jerkmate-smartlink-here.com',
  },
  {
    id: '5',
    username: 'monica_sensual',
    displayName: 'Monica Rey',
    age: 41,
    country: 'France',
    countryCode: 'FR',
    categories: ['mature', 'new'],
    thumbnail: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    isLive: true,
    viewerCount: 940,
    destinationUrl: 'https://your-jerkmate-smartlink-here.com',
  },
  {
    id: '6',
    username: 'sarah_milf_live',
    displayName: 'Sarah Connor',
    age: 45,
    country: 'Australia',
    countryCode: 'AU',
    categories: ['milf', 'popular'],
    thumbnail: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
    isLive: true,
    viewerCount: 1560,
    destinationUrl: 'https://your-jerkmate-smartlink-here.com',
  }
];
